#build:
#	make stop-dev
#	docker-compose -f build/docker-compose.yml up -d --build
#run:
#	docker-compose -f build/docker-compose.yml up -d --build
#stop:
#	docker-compose -f build/docker-compose.yml down -v
#logs:
#	docker-compose -f build/docker-compose.yml logs -f
